name: flrx_validator
description: Validator on steroids
version: 0.1.0
author: Flrx Team <flrx.dev@gmail.com>
homepage: https://flrx.github.io/validator/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_api: ^0.2.5
