name: flrx_validator
description: >
  A powerful, extensible validator package to get validation messages based on a list of rules.
version: 0.3.0
author: Flrx Team <flrx.dev@gmail.com>
homepage: https://flrx.github.io/validator/
repository: https://github.com/flrx/validator
issue_tracker: https://github.com/flrx/validator/issues
documentation: https://flrx.github.io/validator/

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1
  pedantic: ^1.8.0